---
title: "mlearn310_hw3_2_Twitter_Analytics"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(lubridate)
library(scales)
library(tm)
library(stringr)
library(wordcloud)
library(plyr)
library(syuzhet)
library(reshape2)
library(dplyr)
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

### Load Data
```{r load_data, echo=TRUE}
tweets = read.csv("/Users/ravirajmulasa/Documents/personal_workspace/PycharmProjects/Kaggle2Sigma/data/tweet-b-dev-dist.csv", stringsAsFactors = FALSE, header = FALSE)
names(tweets) <- c("SID", "UID", "response", "text")
nohandles <- str_replace_all(tweets$text, "@\\w+", "")
wordCorpus <- Corpus(VectorSource(nohandles))
wordCorpus <- tm_map(wordCorpus, removePunctuation)
wordCorpus <- tm_map(wordCorpus, content_transformer(tolower))
wordCorpus <- tm_map(wordCorpus, removeWords, stopwords("english"))
wordCorpus <- tm_map(wordCorpus, removeWords, c("amp", "2yo", "3yo", "4yo"))
wordCorpus <- tm_map(wordCorpus, stripWhitespace)
wordCorpus <- tm_map(wordCorpus, stemDocument)
tdm <- TermDocumentMatrix(wordCorpus)
tdm
inspect(tdm[2800:2830, 270:280])

```

### Word Cloud
```{r word_cloud, echo=TRUE}
pal <- brewer.pal(9,"YlGnBu")
pal <- pal[-(1:4)]
set.seed(123)
wordcloud(words = wordCorpus, scale=c(5,0.1), max.words=100, random.order=FALSE,rot.per=0.35, use.r.layout=FALSE, colors=pal)

```

### Friends Cloud - Min frequency: 2
```{r friends_cloud_freq_2, echo=TRUE}
friends <- str_extract_all(tweets$text, "@\\w+")
namesCorpus <- Corpus(VectorSource(friends))
set.seed(146)
wordcloud(words = namesCorpus, min.freq=2, scale=c(2,0.5), max.words=40, random.order=FALSE,rot.per=0.01, use.r.layout=FALSE, colors=pal)

```

### Friends Cloud - Min frequency: 1
```{r friends_cloud_freq_1, echo=TRUE}
set.seed(146)
wordcloud(words = namesCorpus, min.freq=1, scale=c(2,0.5), max.words=40, random.order=FALSE,rot.per=0.01, use.r.layout=FALSE, colors=pal)

```

### Sentiment Analysis
```{r sentiment_analysis, echo=TRUE}
mySentiment <- get_nrc_sentiment(tweets$text)
head(mySentiment)
tweets <- cbind(tweets, mySentiment)
head(tweets)
sentimentTotals <- data.frame(colSums(tweets[,c(5:14)]))
names(sentimentTotals) <- "count"
sentimentTotals <- cbind("sentiment" = rownames(sentimentTotals), sentimentTotals)
rownames(sentimentTotals) <- NULL
ggplot(data = sentimentTotals, aes(x = sentiment, y = count)) +
geom_bar(aes(fill = sentiment), stat = "identity") +
theme(legend.position = "none") +
xlab("Sentiment") + ylab("Total Count") + ggtitle("Total Sentiment Score for All Tweets")

```


