---
title: "mlearn310_hw3_5_Ensemble_Methods_Boosting"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(gbm)
library(caret)
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

## Load Data
```{r load_data, echo=TRUE}
mushroom=read.csv(url("https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"), header = FALSE)
names(mushroom) = c("class", "capshape", "capsurface", "capcolor", "bruises", "odor", "gillattachment", "gillspacing", "gillsize", "gillcolor", "stalkshape", "stalkroot", "stalksurfaceabovering", "stalksurfacebelowring", "stalkcolorabovering", "stalkcolorbelowring", "veiltype", "veilcolor", "ringnumber", "ringtype", "sporeprintcolor", "population", "habitat")
nrow(mushroom)
mushroom = na.omit(mushroom)
mushroom$"veiltype" = NULL
nrow(mushroom)
mushroom$sclass[mushroom$class=="e"] = 1
mushroom$sclass[mushroom$class=="p"] = 0
mushroom$"class" = NULL
summary(mushroom)
split = createDataPartition(y=mushroom$sclass, p = 0.8, list=FALSE)
mushroom_train = mushroom[split,]
mushroom_test = mushroom[-split,]
```

## Gradient Boost Tree based model, trees = 2, depth = 3
```{r gradient_boost_tree_25_4, echo=TRUE}
boost <- gbm(sclass~ . , data=mushroom_train, 
             distribution = 'bernoulli', 
             n.trees = 2, 
             interaction.depth = 3)
pred_mushroom_class = predict(boost, mushroom_test, n.trees=2)
pred_mushroom_class_ = ifelse(pred_mushroom_class > mean(pred_mushroom_class), 1, 0)
confusionMatrix(table(pred_mushroom_class_, mushroom_test$sclass))
mean((pred_mushroom_class_ - mushroom_test$sclass)^2)
```

## Gradient Boost Tree based model, trees = 6, depth = 3
```{r gradient_boost_tree_100_3, echo=TRUE}
boost <- gbm(sclass~ . , data=mushroom_train, 
             distribution = 'bernoulli', 
             n.trees = 6, 
             interaction.depth = 3)
pred_mushroom_class = predict(boost, mushroom_test, n.trees=6)
pred_mushroom_class_ = as.integer(ifelse(pred_mushroom_class > mean(pred_mushroom_class), 1, 0))
confusionMatrix(table(pred_mushroom_class_, mushroom_test$sclass))
mean((pred_mushroom_class_ - mushroom_test$sclass)^2)
```

## Gradient Boost Tree based model, trees = 10, depth = 2
```{r gradient_boost_tree_200_3, echo=TRUE}
boost <- gbm(sclass~ . , data=mushroom_train, 
             distribution = 'bernoulli', 
             n.trees = 10, 
             interaction.depth = 2)
pred_mushroom_class = predict(boost, mushroom_test, n.trees=10)
pred_mushroom_class_ = ifelse(pred_mushroom_class > mean(pred_mushroom_class), 1, 0)
confusionMatrix(table(pred_mushroom_class_, mushroom_test$sclass))
mean((pred_mushroom_class_ - mushroom_test$sclass)^2)
```


## Gradient Boost Tree based model, trees = 100, depth = 2
```{r gradient_boost_tree_500_3, echo=TRUE}
boost <- gbm(sclass~ . , data=mushroom_train, 
             distribution = 'bernoulli', 
             n.trees = 100, 
             interaction.depth = 2)
pred_mushroom_class = predict(boost, mushroom_test, n.trees=100)
pred_mushroom_class_ = ifelse(pred_mushroom_class > mean(pred_mushroom_class), 1, 0)
confusionMatrix(table(pred_mushroom_class_, mushroom_test$sclass))
mean((pred_mushroom_class_ - mushroom_test$sclass)^2)
```
# Comments: The no.of trees and depth is inversely proportional.
# Comments: The Accuracy did not increase even the no.of increased from 2 to 6 keeping the depth constant.

